/**
 * Maps Fabric item class names (used as :::ClassName in Mermaid) to their
 * SVG icon filenames in @fabric-msft/svg-icons.
 */
export const FABRIC_ITEM_ICON_MAP: Record<string, string> = {
  Capacity: 'fabric_32_filled.svg',
  Domain: 'fabric_32_filled.svg',
  Workspace: 'fabric_32_color.svg',
  Notebook: 'notebook_32_item.svg',
  Lakehouse: 'lakehouse_32_item.svg',
  Environment: 'environment_32_item.svg',
  SparkJobDefinition: 'spark_job_direction_32_item.svg',
  VariableLibrary: 'variable_library_32_item.svg',
  Eventhouse: 'event_house_32_item.svg',
  Eventstream: 'eventstream_32_item.svg',
  KQLDatabase: 'kql_database_32_item.svg',
  KQLQueryset: 'kql_queryset_32_item.svg',
  KQLDashboard: 'real_time_dashboard_32_item.svg',
  Reflex: 'generic_placeholder_32_item.svg',
  DataPipeline: 'pipeline_32_item.svg',
  Dataflow: 'dataflow_gen2_32_item.svg',
  CopyJob: 'copy_job_32_item.svg',
  Warehouse: 'data_warehouse_32_item.svg',
  SQLEndpoint: 'data_warehouse_32_item.svg',
  MirroredDatabase: 'mirrored_generic_database_32_item.svg',
  SQLDatabase: 'sql_database_32_item.svg',
  Report: 'report_32_item.svg',
  SemanticModel: 'semantic_model_32_item.svg',
  DataAgent: 'data_agent_32_item.svg',
  MLExperiment: 'experiments_32_item.svg',
  UserDataFunction: 'user_data_function_32_item.svg',
  GraphQLApi: 'generic_placeholder_32_item.svg',
};

export const ITEM_DISPLAY_NAMES: Record<string, string> = {
  Capacity: 'Capacity',
  Domain: 'Domain',
  Notebook: 'Notebook',
  Lakehouse: 'Lakehouse',
  Environment: 'Environment',
  SparkJobDefinition: 'Spark Job Definition',
  VariableLibrary: 'Variable Library',
  Eventhouse: 'Eventhouse',
  Eventstream: 'Eventstream',
  KQLDatabase: 'KQL Database',
  KQLQueryset: 'KQL Queryset',
  KQLDashboard: 'Real-Time Dashboard',
  Reflex: 'Activator',
  DataPipeline: 'Data Pipeline',
  Dataflow: 'Dataflow',
  CopyJob: 'Copy Job',
  MountedDataFactory: 'Mounted Data Factory',
  ApacheAirflowJob: 'Apache Airflow Job',
  Warehouse: 'Warehouse',
  SQLEndpoint: 'SQL Endpoint',
  MirroredDatabase: 'Mirrored Database',
  SQLDatabase: 'SQL Database',
  Report: 'Report',
  SemanticModel: 'Semantic Model',
  OrgApp: 'Organizational App',
  MLExperiment: 'ML Experiment',
  DataAgent: 'Data Agent',
  UserDataFunction: 'User Data Function',
  GraphQLApi: 'GraphQL API',
  Workspace: 'Workspace',
};
